### ISSUE TITLE
Adicionar tradução ao e-mail de confirmação

### ISSUE THREAD

**Issue by lukkanog** [MyKidsWatch/MKW.API#53]
# Adicionar tradução ao e-mail de confirmação

### Reprodução
Dado que eu acesse a aplicação
E cadastre um usuário através do _endpoint_ `/v1/Account/register`
Então, o e-mail é enviado com o texto fixo em português (brasileiro).

### Resultado esperado
Que o e-mail seja enviado com os textos no idioma passado como parâmetro  (_query string_ opcional) nesse _endpoint_.

**Comment by wilsonbrandao** [comment]
public static class EmailLangHelper
    {
        private static readonly ResourceManager _rm;

        static EmailLangHelper()
        {
            _rm = new ResourceManager("MKW.Domain.Utility.Language.Email.EmailMessage", Assembly.GetExecutingAssembly());
        }

        public static string? GetString(string key)
        {
            return _rm.GetString(key);
        }

        public static void ChangeCulture(string language)
        {
            var cultureInfo = new CultureInfo(language);

            CultureInfo.CurrentCulture = cultureInfo;
            CultureInfo.CurrentUICulture = cultureInfo;
        }
    }

**Comment by wilsonbrandao** [comment]
`    public static class EmailLangHelper
    {
        private static readonly ResourceManager _rm;

        static EmailLangHelper()
        {
            _rm = new ResourceManager("MKW.Domain.Utility.Language.Email.EmailMessage", Assembly.GetExecutingAssembly());
        }

        public static string? GetString(string key)
        {
            return _rm.GetString(key);
        }

        public static void ChangeCulture(string language)
        {
            var cultureInfo = new CultureInfo(language);

            CultureInfo.CurrentCulture = cultureInfo;
            CultureInfo.CurrentUICulture = cultureInfo;
        }
    }`

Criei a classe helper e implementei os arquivois .resx pra intercionalização. 

`public async Task<ActionResult<BaseResponseDTO<ReadUserDTO>>> RequestEmailKeycode([FromBody] RequestKeycodeDTO keycodeRequest, [FromQuery] string language = "pt-BR")
        {
            var result = await _service.RequestEmailKeycodeAsync(keycodeRequest, language);
            return result.IsSuccess ? Ok(result) : BadRequest(result);
        }`

Adicionei o parametro de query string language tmb aos endpoints que enviam algum tipo de email
