### ISSUE TITLE
[Feature request] Uniformização das respostas de conteúdo

### ISSUE THREAD

**Issue by FelipeDominguesB** [MyKidsWatch/MKW.API#60]
A busca de conteúdo realizada através da API, atualmente limitada apenas à filmes feita através dos métodos GetMovie e e GetMovieByName da controller Movie Controller, tem um retorno especificado de um MovieDTO. Acredito que seria mais interessante a criação de um modelo de dados genérico que pudesse ser populado por mais de um tipo de provedor, tendo em vista que o modelo de MovieDTO atual foca em dar suporte apenas ao contrato do TMDB. 

Adicionalmente, acredito que essa mudança deveria ser realizada dentro de uma nova controller dedicada à busca de conteúdos de múltiplas plataformas.

**Comment by pedroalcantara-net** [comment]
Implementada nova interface de busca de conteúdo, unificando as plataformas diferentes no fluxo da ContentController.
