### ISSUE TITLE
[Feature request] Endpoint de perfil

### ISSUE THREAD

**Issue by lukkanog** [MyKidsWatch/MKW.API#62]
# Endpoint GET de Profile

Sugestão de contrato:

```json
{
    "id": 0,
    "userId": 0,
    "imageUrl": "image.png",
    "name": "firstName and lastName together",
    "username": "lorem.ipsum01",
    "children": [
         {
             "id": 0,
             "genderId": 0,
             "ageRangeId": 0
         }
    ],
    "awards": [
        {
            "name": "gold",
            "quantity": 32
        },
        {
            "name": "silver",
            "quantity": 15
        },
        {
            "name": "bronze",
            "quantity": 27
        },
    ]
}
```

Sugiro que no endpoint do perfil não traga as _reviews_ do mesmo, ao invés disso, a gente faça outro _endpoint_ para as review de um usuário específico. Acho que nesse caso podemos seguir o mesmo contrato definido para a requisição de _reviews_:

```json
[
  {
    "id": 0,
    "person": {
      "id": 0,
      "name": "Wilson brandão",
      "imageUrl": "path/path2.png"
    },
    "content": {
      "id": 0,
      "name": "Pocoyo", 
      "imageUrl": "path/path.png",
      "platformId": 0
    },
    "goldenAwards": 0,
    "silverAwards": 0,
    "bronzeAwards": 0,

    "commentsQuantity": 0,

 

    "title": "Horroroso de ruim",
    "text": "Lorem ipsum dolor sit amet adisciping consectetur elit",
    "stars": 0,
    "createDate": "2023-08-08T00:00:00Z",
    "edited": true
  }  
]
```

@wilsonbrandao O que acha?

**Comment by lukkanog** [comment]
@wilsonbrandao Editei a sugestão do contrato para adicionar o `username`

**Comment by lukkanog** [comment]
@wilsonbrandao Editei a sugestão do contrato para adicionar os prêmios do usuário

**Comment by wilsonbrandao** [comment]
@lukkanog Fiquei na duvida do primeiro id no endpoint do profile,  atual a gente não tem nenhuma tabela que relacione todos esses dados e persista o id. Podemos tirar ele e tomar como base o userId?

**Comment by lukkanog** [comment]
@wilsonbrandao tinha pensado em ser o id do profile (que herda da BaseEntity), mas pode ser sim

**Comment by wilsonbrandao** [comment]
![image](https://github.com/MyKidsWatch/MKW.API/assets/69026669/7ad899e5-64de-44c0-8194-98d5295729d8)
