### ISSUE TITLE
[Bug] Movie/:id está retornando propriedades nulas

### ISSUE THREAD

**Issue by FelipeDominguesB** [MyKidsWatch/MKW.API#63]
Conforme o titulo sugere, a busca de filmes por id tem retornando os campos backdropPath, originalLanguage, originalTitle, voteAverage e voteCount nulas

**Comment by pedroalcantara-net** [comment]
Como as propriedades originais do Json que vinha do TMDb tinha "_" no nome, o HttpClient não estava convertendo corretamente ao fazer o GetFromJsonAsync<>.
Corrigido, realizarei alterações nos outros métodos que requisitam essa API.

**Comment by pedroalcantara-net** [comment]
Corrigido. DIsponível em Staging.
