### ISSUE TITLE
[Feature request] Informações de user no retorno de relevant reviews

### ISSUE THREAD

**Issue by FelipeDominguesB** [MyKidsWatch/MKW.API#64]
Retorno de relevant reviews precisa trazer informações do usuário que criou a análise (Atualmente apenas informações de profile são acessíveis no response) 

![image](https://github.com/MyKidsWatch/MKW.API/assets/37378456/51d85126-c807-4020-b3c3-3ac266bef7f5)

**Comment by pedroalcantara-net** [comment]
Implementado. Retorno informa username e nome do usuário
