### ISSUE TITLE
[Feature request] Funcionalidades adicionais para o sistema de report

### ISSUE THREAD

**Issue by FelipeDominguesB** [MyKidsWatch/MKW.API#94]
Vou condensar alguns pedidos adicionais nesse feature request, visto que todos são necessários para o funcionamento básico apropriado do sistema de report

1 - Busca paginada das informações de report

Implementar uma busca paginada que traz as seguintes informações: id do report, data de criação, tipo de report (profile, review ou comment), usuário responsável pela criação, usuário criador do que está sendo denunciado. Trazer também informações da paginação (page index, page size e total count). Busca deve poder deixar filtrar por status do report.

2 - Atualização de um report

Implementar um método para atualização do status de um report, necessário para que os usuários administradores possam dar baixa em reports que já foram tratados.

3 - Permitir realizar report de profile

Criar nova coluna na tabela de report, deve segurar a informação de perfil sendo reportado. Não confundir com a informação de quem foi responsável por criar a review.

**Comment by pedroalcantara-net** [comment]
Pedidos 2 e 3 implementados e disponíveis em Staging.

**Comment by lukkanog** [comment]
@pedroalcantara-net Vi que você implementou o item 3 com o `PersonId`. Poderiamos utilizar o `UserId` na requisição?

Digo isso porque os outros endpoints que tem algo relacionado ao usuário estão utilizando o `UserId`. O endpoint  `GET /v1/Profile`, que usamos na tela do perfil, não traz o `PersonId`.

Endpoints que estão utilizando o `UserId`:
- `GET /v1/Review/User/{userId}`

Outra opção seria alterar o endpoint `GET /v1/Profile` para trazer o id do objeto `Person`, e não do `User`. Porém isso também resultaria em uma alteração no frontend.

<hr>

@pedroalcantara-net  @wilsonbrandao Vejam aí o que faz mais sentido para vocês, mas basicamente cada endpoint está trazendo/solicitando uma coisa. Precisamos decidir se vamos usar o `PersonId`ou o `UserId` nessas requisições e padronizar isso.

**Comment by pedroalcantara-net** [comment]
@FelipeDominguesB pedido 1 implementado e disponível em Staging. Atente-se ao novo contrato informando a página, quantidade de páginas e tamanho das páginas, além dos resultados.

@lukkanog `GET /v1/Profile` retorna o PersonId, além do UserId. Centralizaremos as requisições em PersonId, já que UserId é relacionado às tabelas do Identity e não à entidade do usuário que se relaciona às outras entidades.
