### ISSUE TITLE
[Feature request] Adição de nova propriedade no payload de informações do usuário

### ISSUE THREAD

**Issue by FelipeDominguesB** [MyKidsWatch/MKW.API#95]
Payload de busca de informação do usuário pelo token deve retornar se o usuário em questão é administrador ou não. Essa informação é necessária para verificar se ele deve ter acesso à interface de administrador.

**Comment by wilsonbrandao** [comment]
adicionei essa prop no DTO do endpoint byToken

![image](https://github.com/MyKidsWatch/MKW.API/assets/69026669/f051254d-baff-4416-ab05-6ad98fd4853f)
